openapi: 3.0.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /books/create:
    post:
      tags:
      - controller
      operationId: createBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestCreateBookDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BookDTO"
  /books/maxAwards:
    get:
      tags:
      - controller
      operationId: getMaxAwards
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AuthorDTO"
  /books/category/{genre}:
    get:
      tags:
      - controller
      operationId: getAllBooksByGenre
      parameters:
      - name: genre
        in: path
        required: true
        schema:
          type: string
          enum:
          - NOVEL
          - FANTASY
          - ROMANCE
          - PROGRAMMING
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookDTO"
  /:
    get:
      tags:
      - test-controller
      operationId: test
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    RequestCreateBookDTO:
      type: object
      properties:
        title:
          type: string
        isbn:
          type: string
        genre:
          type: string
          enum:
          - NOVEL
          - FANTASY
          - ROMANCE
          - PROGRAMMING
        publishYear:
          type: integer
          format: int32
        authorId:
          type: integer
          format: int64
      required:
      - authorId
      - isbn
      - publishYear
      - title
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nationality:
          type: string
        birthDate:
          type: string
          format: date
        awards:
          type: integer
          format: int32
    BookDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        isbn:
          type: string
        genre:
          type: string
          enum:
          - NOVEL
          - FANTASY
          - ROMANCE
          - PROGRAMMING
        publishYear:
          type: integer
          format: int32
        author:
          $ref: "#/components/schemas/Author"
    AuthorDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nationality:
          type: string
        birthDate:
          type: string
          format: date
        awards:
          type: integer
          format: int32
